main: "de.bypixeltv.novautils.Main"
name: "NovaUtils"
version: "1.0"
api-version: "1.20"

author: "byPixelTV"
description: "A utility Minecraft plugin!"
website: "https://bypixeltv.de"

libraries:
  - "dev.jorel:commandapi-bukkit-shade:9.3.0"
  - "dev.jorel:commandapi-bukkit-kotlin:9.3.0"
  - "net.axay:kspigot:1.20.2"
  - "com.zaxxer:HikariCP:5.1.0"
  - "org.mariadb.jdbc:mariadb-java-client:3.3.2"

depend:
  - PlaceholderAPI
  - WorldGuard